### PR TITLE
Add the option of "--xwalk-apk-url" when creating Cordova project

### PR DESCRIPTION
**Pull request by fujunwei**
The "--xwalk-apk-url" configure the download URL of the Crosswalk runtime
library in the Android manifest.
./bin/create HelloWorld org.example.HelloWorld HelloWorld
    --xwalk-shared-library --xwalk-apk-url=http://host/XWalkRuntimeLib.apk

### CODE REVIEW

**Comment by fujunwei** [comment]
@huningxin  @lincsoon PTAL, Thanks.

**Comment by lincsoon** [comment]
LGTM

**Comment by huningxin** [comment]
What will happen if only use `--xwalk-apk-url`? Do we need limit it to be used with `--xwalk-shared-library`?

**Comment by lincsoon** [comment]
Basically `--xwalk-apk-url` just insert a meta-data element into the application tag in the Android manifet, it won't hurt anything event not in shared mode. But for guiding the users, it also makes some sense to give some hint that this option doesn't work alone.

**Comment by fujunwei** [comment]
Thanks, Done.

**Comment by huningxin** [comment]
LGTM. Thanks. I am going to merge it.

**Pull request merged**
