### PR TITLE
Initial commit for cocos2d-cordova-crosswalk

### PR DESCRIPTION
**Pull request by kurli**
Crosswalk cocos2d optimization based on crosswalk-cordova-android v10

### CODE REVIEW

**Comment by kurli** [comment]
ping @halton  @baleboy @zhiqiangyu
I have created a new branch named cocos2d-crosswalk-cordova on this repo, Please have a review.

**Comment by kurli** [comment]
ping @js0701 @gaochun Please have a review

**Comment by js0701** [comment]
LGTM

**Comment by kurli** [comment]
@huningxin Can we merge this?

**Pull request merged**
