### PR TITLE
Add the option of --sharedCrosswalk to use Crosswalk shared mode

### PR DESCRIPTION
**Pull request by fujunwei**
Use the option of --sharedCrosswalk to create a shared mode Crosswalk Cordova project. It isn't used together with --shared.

### CODE REVIEW

**Comment by fujunwei** [comment]
@huningxin @wang16 PTAL, thanks.

**Comment by halton** [comment]
Just a comment: `--sharedCrosswalk` and `shared` is very confused by user, even there is description or document for that. Any better option names?

**Comment by fujunwei** [comment]
Yes, how about xwalksharedLibrary?

**Comment by halton** [comment]
Still not so straight forward. Question: Is this option needed? Should not crosswalk check whether it is shard mode or embedding api mode on the fly? Add @lincsoon @wang16 in loop

**Comment by lincsoon** [comment]
In new implementation, there are 2 parallel directories named xwalk_share_library and xwalk_core_library, we plan to release both of them in crosswalk build. The new option is to help developers of Embedding API or Cordova to choose which library to link when creating their project. Regardless which library used in built time, the final crosswalk app could check whether it is in shared mode and check compatibility on run time.

**Comment by huningxin** [comment]
How about `--use-xwalk-shared-library` or `--xwalk-shared-library`?

**Comment by halton** [comment]
@lincsoon thanks for you explanation, much clear now. @fujunwei please update this PR with those information in.

@huningxin I prefer more for `--use-xwalk-shared-library`.

**Comment by lincsoon** [comment]
I prefer --xwalk-shared-library :)
Any way, --xxx-xxx-xxx (no upper case) is more normalized as an option.

**Comment by halton** [comment]
`--xwalk-shared-library` either fine to me, it is your call to decide.

**Comment by huningxin** [comment]
Let's go `--xwalk-shared-library`.

**Comment by fujunwei** [comment]
Thanks,　the commit was updated. @lincsoon is the directory named xwalk_shared_library or xwalk_share_library?

**Comment by lincsoon** [comment]
It's xwalk_shared_library

**Comment by halton** [comment]
LGTM.

One common issue: seems the python does not follow google python style(at least it exceed 80 char line width), do you have plan to modify that?

**Comment by fujunwei** [comment]
The Cordova upstream also don't follow the style, maybe  we need  lot of work to modify those.

**Comment by halton** [comment]
@fujunwei thanks for let me know about the style.

**Comment by huningxin** [comment]
LGTM. Thanks for the PR. I am going to merge it.

**Pull request merged**
